<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Birthday_day</name>
   <tag></tag>
   <elementGuidId>561ef40e-fdf0-4422-b61c-1bc4a2bdaeb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;day&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='day']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96665458-e414-4167-9ff5-b42aa098360b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>day</value>
      <webElementGuid>5f4c9a44-999f-4d11-a177-990a9c91e176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Day</value>
      <webElementGuid>bb6afb2f-06b7-4961-bdd1-ade3a76b9a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>e0799d23-24d9-4224-9fd4-df2a0d02ec38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ui fluid container&quot;]/div[@class=&quot;ui fluid container main-content&quot;]/form[@class=&quot;ui form segment custom-form-container&quot;]/div[@class=&quot;two fields&quot;]/div[@class=&quot;field&quot;]/div[@class=&quot;ui field&quot;]/div[@class=&quot;three fields custom-address-container&quot;]/div[@class=&quot;ui small icon input&quot;]/input[1]</value>
      <webElementGuid>eaf990d4-b0a5-4ca5-b7ad-0fcaaba7509f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='day']</value>
      <webElementGuid>e02d763d-4360-471d-b39b-c8e237dce253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/div[2]/form/div[12]/div[2]/div/div/div/input</value>
      <webElementGuid>4e29502e-52fd-4110-8184-6cd5d8410076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[2]/div/div/div/input</value>
      <webElementGuid>45c986fd-7b7b-4db7-ae53-43d24f9e5ba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'day' and @placeholder = 'Day' and @type = 'number']</value>
      <webElementGuid>086b890c-71ea-4734-ba4f-ecc50ae1bbc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
