<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Calendar_users icon</name>
   <tag></tag>
   <elementGuidId>c60e5678-14d0-488e-9aba-154377c97038</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-nav']/div[3]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.users.icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c4ddfb10-108a-4c3c-95ea-4d350ca81730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>users icon</value>
      <webElementGuid>3d5f8d8a-e4d3-4ceb-8223-bfb02cfcf7f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-nav&quot;)/div[@class=&quot;menu-item-wrapper&quot;]/a[@class=&quot;item&quot;]/i[@class=&quot;users icon&quot;]</value>
      <webElementGuid>b4477742-f164-4918-a878-d55c36dea938</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-nav']/div[3]/a/i</value>
      <webElementGuid>b1475b1f-0f10-4c70-aa12-b56d3b5bbe2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/i</value>
      <webElementGuid>19acddb6-d32d-4af8-83b8-3d8cd11910df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
