<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Calendar_users icon</name>
   <tag></tag>
   <elementGuidId>139ce542-591a-4a77-bdb5-3199bdd5fc1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.users.icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-nav']/div[3]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>8a385f88-5b78-474e-aa99-37da04cadd91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>users icon</value>
      <webElementGuid>24049188-0882-466b-ac87-4b1931d0790f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-nav&quot;)/div[@class=&quot;menu-item-wrapper&quot;]/a[@class=&quot;item&quot;]/i[@class=&quot;users icon&quot;]</value>
      <webElementGuid>9897d067-8082-468c-ba7a-4294090f695b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-nav']/div[3]/a/i</value>
      <webElementGuid>3a46f8e3-c6b3-451a-8468-d2a4c54525fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/i</value>
      <webElementGuid>c683e774-1889-42cc-b3bf-f10392839fa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
