<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Kunj Kaneria_edit icon</name>
   <tag></tag>
   <elementGuidId>54d2959d-3819-4f04-a4aa-e7a3b17f015f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.edit.icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dashboard-toolbar']/div[2]/div/a/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>eaa8af20-dfbc-4050-bb9d-d38e6dd2be9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>61216c27-495d-47c4-ba23-d929346220d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>edit icon</value>
      <webElementGuid>37fb6145-54c0-486e-942c-db6f63f28e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard-toolbar&quot;)/div[@class=&quot;ui right secondary pointing menu toolbar-container&quot;]/div[@class=&quot;item view-page-toolbar&quot;]/a[1]/button[@class=&quot;ui icon button&quot;]/i[@class=&quot;edit icon&quot;]</value>
      <webElementGuid>1c97b956-ce7f-4573-b06e-934033bf04a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard-toolbar']/div[2]/div/a/button/i</value>
      <webElementGuid>61bb432c-8ec4-4dff-8bec-4327d39feb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/button/i</value>
      <webElementGuid>a24b375d-4091-4f6e-bafe-8a1230e97f36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
